name: PyPI Publish

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.ipynb'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-n-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 'pypy3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install build tool
      run: pip install build

    - name: Build distributions
      run: python -m build --sdist --wheel --outdir dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
